config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'pages#home'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :user
validates :productname,  presence: true
validates :productprice, presence:true
validates :productstatus,presence:true

validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
has_many :products

before_save {self.email = email.downcase}
validates :username, presence: true,
          uniqueness: {case_sensitive: false},
          length: {minimum: 3, maximum: 25}

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :email, presence:true, length: {maximum: 105},
          uniqueness:{case_sensitive: false},
          format: {with: VALID_EMAIL_REGEX}

validates :status, presence:true
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = User.first

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:productname, :productprice, :productstatus)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for (user, options = {size: 80})
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: " rounded-circle " )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <%= link_to "Octek-Trading", root_path, class: "navbar-brand", id: "logo"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

        <%= link_to "Products", products_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Octek-Traders", users_path , class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TradingPoint</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Octek-Trading</title>
    <link rel="stylesheet" href="">


</head>

<body>


  <div class="jumbotron center ">
  <h1 class="display-4">Octek-Trading</h1>


  <%= link_to "Sign up now", new_user_path , class: "btn btn-info btn-lg" %>
  </div>


</body>

</html>

app/views/products/_form.html.erb
<div class="center">
    <div class="col-xl-12">

<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
  <div class="control-label col-sm-2">
        <%= form.label :Name, class: "label1" %>
      </div>
      <div class="col-sm-12">
      <%= form.text_field :productname ,class:"form-control" , placeholder: "Enter Your product name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= form.label :Price, class: "label1" %>
    </div>
    <div class="col-sm-12">
    <%= form.number_field :productprice, rows: 4 ,class:"form-control" , placeholder: "Enter your product price", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= form.label :Availability, class: "label1" %>
    </div>
    <div class="col-sm-12">
    <%= form.check_box :productstatus, rows: 8,class: "checkbox checkbox1" , autofocus: true %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-10">
      <%= form.submit(@product.new_record? ? "Sign up" : "Update Account", class: 'btn btn-primary btn-lg') %>
    </div>
  </div>

<% end %>

</div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center productlisth1">List of Products</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Productname</th>
      <th>Productprice</th>
      <th>Productstatus</th>
      <th>Created By</th>
      <th colspan="3"></th>


    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.productname , product_path(product) %></td>
        <td><%= link_to product.productprice , product_path(product) %></td>
        <% if (product.productstatus == true) %>
            <td>Available</td>
            <% else %>
              <td>Not Available</td>
          <%end %>

        <td><%= product.user.username if product.user %></td>
        <td><%= link_to 'Show', product ,  class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-xs btn-warning" %></td>
        <td><%= link_to 'Destroy', product, class: "btn btn-xs btn-danger" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="newproductbtn  center">
<%= link_to 'New Product', new_product_path , class: "btn btn-xs btn-success " %>
</div>

app/views/products/new.html.erb
<h1 class="center">New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productname:</strong>
  <%= @product.productname %>
</p>

<p>
  <strong>Productprice:</strong>
  <%= @product.productprice %>
</p>

<p>
  <strong>Productstatus:</strong>
  <%= @product.productstatus %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-1">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
          <%= pluralize(obj.errors.count,"error") %>
            Probhited this article from saved:
        </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li style="font-size: 20px;"> <%= msg %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="center">
    <div class="col-xl-12">

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
<div class="control-label col-sm-2">
      <%= form.label :username, class: "label1" %>
    </div>
    <div class="col-sm-12">
    <%= form.text_field :username ,class:"form-control" , placeholder: "Enter user name", autofocus: true %>
  </div>
</div>


<div class="form-group">
  <div class="control-label col-sm-2">
    <%= form.label :email, class: "label1" %>
  </div>
  <div class="col-sm-12">
  <%= form.email_field :email, rows: 4 ,class:"form-control" , placeholder: "Enter email", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= form.label :password, class: "label1" %>
  </div>
  <div class="col-sm-12">
  <%= form.password_field :password, rows: 8 ,class:"form-control" , placeholder: "Enter Password", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= form.label :status, class: "label1" %>
  </div>
  <div class="col-sm-12">
  <%= form.number_field :status, rows: 8 ,class:"form-control" , placeholder: "Enter 1 for buyer & 2 for seller", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-10">
    <%= form.submit(@user.new_record? ? "Sign up" : "Update Account", class: 'btn btn-primary btn-lg') %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<h1 align ="center"> All Octek Traders </h1>
<div align = "center">

  <% @users.each do |user| %>
      <ul class="listing center">
        <div class="row">
          <div class="card card-body bg-light  col-md-8 userdiv" >
            <li> <%= link_to  gravatar_for(user), user_path(user) %> </li>
            <li class="article-title">
              <%= link_to user.username, user_path(user) %>
            </li>
            <li> <small> <%= pluralize(user.products.count, "product") if user.products %> </small>
              <% if (user.status == 1) %>
                  <td>Buyer</td>
                  <% else %>
                    <td>Seller</td>
                <%end %>
             </li>

            <li> <%= link_to "Edit This User" ,edit_user_path(user),class: "btn btn-warning btn-sm" %>
             <%= link_to "Delete this User" , user_path(user),class: "btn btn-danger btn-sm", method: :delete,
            data: {confirm: "Are you sure to delete this user & all this articles?"} %> </li>



          </div>
        </div>
      </ul>

  <% end %>
</div>


<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 align="center"> Welcome to signup Page</h1>



<%= render 'form', user: @user %>

<!-- <%= link_to '<- Back', users_path, class: "btn btn-success btn-lg" %> -->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1 align = "center"> Welcome to <%= @user.username %>'s page </h1>
<div  class="row">
  <div class="col-md-4 col-md-offset-4 dp">
    <%=  gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align = "center" > <%= @user.username %>'s Products </h4>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>